--=========================================================================dd==
--  TABLE DELETION
--=========================================================================dd==
DROP TABLE images;
DROP TABLE geometry;
DROP TABLE entries;

--=========================================================================dd==
--  TABLE CREATION
--=========================================================================dd==
CREATE TABLE entries
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(64),
    description CLOB
);

CREATE TABLE images
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entry_id    NUMBER(5),
    title       VARCHAR2(64),
    description CLOB,
    image       ORDSYS.ORDImage,
    image_si    ORDSYS.SI_StillImage,
    image_ac    ORDSYS.SI_AverageColor,
    image_ch    ORDSYS.SI_ColorHistogram,
    image_pc    ORDSYS.SI_PositionalColor,
    image_tx    ORDSYS.SI_Texture,

    -- Foreign key constraints
    CONSTRAINT FK_images_entry
        FOREIGN KEY (entry_id)
            REFERENCES entries (id)
);

CREATE TABLE geometry
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entry_id      NUMBER(5),
    layer         NUMBER(5),
    type          VARCHAR2(16),
    internal_type VARCHAR2(16),
    data          SDO_GEOMETRY,

    -- Foreign key constraints
    CONSTRAINT FK_geometry_entry
        FOREIGN KEY (entry_id)
            REFERENCES entries (id)
);

--=========================================================================dd==
--  METADATA CREATION
--=========================================================================dd==

DELETE
FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'GEOMETRY'
  AND COLUMN_NAME = 'DATA';

INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('geometry', 'data', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X', 0, 4096, 0.1), SDO_DIM_ELEMENT('Y', 0, 4096, 0.1)),
        NULL);
